"""
import_materials.py — jednorazowy import surowców z hexah API.
Uruchom: python import_materials.py
Bezpieczny do wielokrotnego uruchomienia (pomija istniejące nazwy).
"""
import os
import sys

# Flask app context
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from main import create_app
from models import db, Item

# ── Dane surowców ──────────────────────────────────────────────────────────────
# Każdy wpis: (nazwa, opis, kategoria)

ITEMS = [
    # ── METALE — bryłki ────────────────────────────────────────────────────────
    ("Bryłka żelaza", "Srebrzysty, kowalny, dość twardy i ciężki metal. Bryłka.", "METALE"),
    ("Bryłka cynku", "Błękitnobiały, kruchy metal. Bryłka.", "METALE"),
    ("Bryłka miedzi", "Czerwonobrunatny, bardzo plastyczny, kowalny i lekki metal. Bryłka.", "METALE"),
    ("Bryłka cyny", "Srebrzysty, pospolity, plastyczny i kowalny metal nieco lżejszy od srebra. Bryłka.", "METALE"),
    ("Bryłka srebra", "Srebrzysty metal szlachetny, bardzo ciągliwy i kowalny, nieco twardszy od złota. Bryłka.", "METALE"),
    ("Bryłka złota", "Żółty metal szlachetny, bardzo ciągliwy, najbardziej kowalny ze znanych metali. Bryłka.", "METALE"),
    ("Bryłka mithrilu", "Srebrzysty metal o dobrej kowalności podobny do srebra, jednak lżejszy od niego o około połowę. Bryłka.", "METALE"),
    ("Bryłka lunaridium", "Czarny, matowy, z maleńkimi srebrzystymi drobinkami metal, niebywale ciężki i niezwykle trudny w obróbce, za to bardzo wytrzymały.", "METALE"),
    ("Bryłka adamantytu", "Niebiesko-srebrzysty, rzadki metal; bardzo lekki, a przy tym niezwykle wytrzymały, jednak trudny do obróbki. Bryłka.", "METALE"),
    ("Bryłka węgla", "Czarna, matowa, krucha i palna skała osadowa. Bryłka.", "METALE"),
    # ── METALE — sztabki ───────────────────────────────────────────────────────
    ("Sztabka żelaza", "Srebrzysty, kowalny, dość twardy i ciężki metal. Sztabka.", "METALE"),
    ("Sztabka adamantytu", "Niebiesko-srebrzysty metal; bardzo lekki, a przy tym niezwykle wytrzymały, jednak trudny do obróbki. Sztabka.", "METALE"),
    ("Sztabka stali", "Srebrzysty, kowalny, dość twardy i ciężki stop żelaza z węglem. Sztabka.", "METALE"),
    ("Sztabka miedzi", "Czerwonobrunatny, bardzo plastyczny, kowalny i lekki metal. Sztabka.", "METALE"),
    ("Sztabka cyny", "Srebrzysty, pospolity, plastyczny i kowalny metal nieco lżejszy od srebra. Sztabka.", "METALE"),
    ("Sztabka cynku", "Błękitnobiały, kruchy metal. Sztabka.", "METALE"),
    ("Sztabka srebra", "Srebrzysty metal szlachetny, bardzo ciągliwy i kowalny, nieco twardszy od złota. Sztabka.", "METALE"),
    ("Sztabka złota", "Żółty metal szlachetny, bardzo ciągliwy, najbardziej kowalny ze znanych metali. Sztabka.", "METALE"),
    ("Sztabka mithrilu", "Srebrzysty metal o dobrej kowalności podobny do srebra, jednak lżejszy od niego o około połowę. Sztabka.", "METALE"),
    ("Sztabka lunaridium", "Czarny, matowy, z maleńkimi srebrzystymi drobinkami metal, niebywale ciężki i niezwykle trudny w obróbce, za to bardzo wytrzymały. Sztabka.", "METALE"),
    ("Sztabka mosiądzu", "Pomarańczowożółty, kowalny, dość twardy i ciężki stop miedzi z cynkiem. Sztabka.", "METALE"),
    ("Sztabka brązu", "Brązowy, kowalny, dość twardy i ciężki stop miedzi z cyną. Sztabka.", "METALE"),
    ("Sztabka elfiej stali", "Ciemnosrebrzysty, kowalny, dość twardy i nieco lżejszy od stali stop żelaza z mithrilem. Sztabka.", "METALE"),
    ("Sztabka lazurostali", "Ciemnosrebrzysty z wyraźnym lazurowym połyskiem, kowalny, twardy, sprężysty i lżejszy od stali stop żelaza z adamantytem. Sztabka.", "METALE"),
    # ── METALE — surowe ────────────────────────────────────────────────────────
    ("Żelazo", None, "METALE"),
    ("Złoto", None, "METALE"),
    ("Węgiel", None, "METALE"),
    # ── KRYSZTAŁY — nieoszlifowane ─────────────────────────────────────────────
    ("Kamień mocy", "Przejrzysty, niebieski kryształ. Znak zodiaku: Lewiatan. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Gorzknik", "Nieco mętny, granatowy kryształ. Znak zodiaku: Mandragora. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Kryształ samoświetlny", "Bardzo rzadki kryształ mający zdolność pochłaniania światła solimusowego i następnie oddawania go w mroku. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Cytryn", "Mętny, żółty kryształ. Znak zodiaku: Feniks. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Krwawnik", "Mętny, czerwony kryształ. Znak zodiaku: Ryś. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Ciernik", "Przejrzysty, błękitny kryształ. Znak zodiaku: Jednorożec. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Natan", "Półprzejrzysty, ciemnozielony kryształ o niejednolitym wybarwieniu. Znak zodiaku: Gorgona. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Smocze oko", "Półprzezroczysty, pomarańczowy kryształ z czarnym prążkowaniem. Znak zodiaku: Smok. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Szlachetnik", "Półprzejrzysty, fioletowy kryształ o niejednolitym wybarwieniu. Znak zodiaku: Gryf. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Złotnik", "Mętny, złotawy kryształ. Znak zodiaku: Krab. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Łzawnik", "Półprzejrzysty, jasnoozielony kryształ o niejednolitym wybarwieniu. Znak zodiaku: Hydra. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Kryształ górski", "Mętny kryształ o odcieniu chłodnej bieli. Znak zodiaku: Cyklop. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Mgielnik", "Nieco mętny, szaroniebieski kryształ. Znak zodiaku: Kraken. Nieoszlifowany.", "KRYSZTAŁY"),
    ("Kryształ ogniskujący", "Kryształ mający zastosowanie w produkcji broni palnej. Nieoszlifowany.", "KRYSZTAŁY"),
    # ── KRYSZTAŁY — oszlifowane ────────────────────────────────────────────────
    ("Oszlifowany kamień mocy", "Przejrzysty, niebieski kryształ. Znak zodiaku: Lewiatan. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany gorzknik", "Nieco mętny, granatowy kryształ. Znak zodiaku: Mandragora. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany kryształ samoświetlny", "Bardzo rzadki kryształ mający zdolność pochłaniania światła solimusowego i następnie oddawania go w mroku. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany cytryn", "Mętny, żółty kryształ. Znak zodiaku: Feniks. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany krwawnik", "Mętny, czerwony kryształ. Znak zodiaku: Ryś. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany ciernik", "Przejrzysty, błękitny kryształ. Znak zodiaku: Jednorożec. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany natan", "Półprzejrzysty, ciemnozielony kryształ o niejednolitym wybarwieniu. Znak zodiaku: Gorgona. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowane smocze oko", "Półprzezroczysty, pomarańczowy kryształ z czarnym prążkowaniem. Znak zodiaku: Smok. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany szlachetnik", "Półprzejrzysty, fioletowy kryształ o niejednolitym wybarwieniu. Znak zodiaku: Gryf. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany złotnik", "Mętny, złotawy kryształ. Znak zodiaku: Krab. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany łzawnik", "Półprzejrzysty, jasnoozielony kryształ o niejednolitym wybarwieniu. Znak zodiaku: Hydra. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany kryształ górski", "Mętny kryształ o odcieniu chłodnej bieli. Znak zodiaku: Cyklop. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany mgielnik", "Nieco mętny, szaroniebieski kryształ. Znak zodiaku: Kraken. Oszlifowany.", "KRYSZTAŁY"),
    ("Oszlifowany kryształ ogniskujący", "Dość rzadki kryształ mający zastosowanie w produkcji broni palnej. Oszlifowany.", "KRYSZTAŁY"),
    # ── KAMIENIE SZLACHETNE — nieoszlifowane ──────────────────────────────────
    ("Ametyst", "Fioletowy kamień szlachetny tradycyjnie kojarzony z potęgą umysłu. Nieoszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Diament", "Biały kamień szlachetny tradycyjnie kojarzony z siłą osobowości. Nieoszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Rubin", "Czerwony kamień szlachetny tradycyjnie kojarzony z potęgą i siłą. Nieoszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Szafir", "Niebieski kamień szlachetny tradycyjnie kojarzony z gracją i zwinnością. Nieoszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Szmaragd", "Zielony kamień szlachetny tradycyjnie kojarzony z odpornością. Nieoszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Opal", "Błękitny kamień szlachetny tradycyjnie kojarzony z bystrością zmysłów. Nieoszlifowany.", "KAMIENIE SZLACHETNE"),
    # ── KAMIENIE SZLACHETNE — oszlifowane ─────────────────────────────────────
    ("Oszlifowany ametyst", "Fioletowy kamień szlachetny tradycyjnie kojarzony z potęgą umysłu. Oszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Brylant", "Biały kamień szlachetny tradycyjnie kojarzony z siłą osobowości. Oszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Oszlifowany rubin", "Czerwony kamień szlachetny tradycyjnie kojarzony z potęgą i siłą. Oszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Oszlifowany szafir", "Niebieski kamień szlachetny tradycyjnie kojarzony z gracją i zwinnością. Oszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Oszlifowany szmaragd", "Zielony kamień szlachetny tradycyjnie kojarzony z odpornością. Oszlifowany.", "KAMIENIE SZLACHETNE"),
    ("Oszlifowany opal", "Błękitny kamień szlachetny tradycyjnie kojarzony z bystrością zmysłów. Oszlifowany.", "KAMIENIE SZLACHETNE"),
    # ── ROŚLINY I ZIOŁA ────────────────────────────────────────────────────────
    ("Kocia miętka", "Ceniona za właściwości poprawiające refleks i precyzję ruchów. Przydatna także w kuchni.", "ROŚLINY"),
    ("Mądroziele", "Ceniona za działanie poprawiające koncentrację i rozjaśniające umysł. Gorzkawy smak.", "ROŚLINY"),
    ("Lawendzik", "Ceniony za walory smakowe oraz właściwości poprawiające dobrostan psychiczny.", "ROŚLINY"),
    ("Szalej", "W zależności od dawki środek pobudzający, narkotyk lub trucizna. Pikantny w smaku.", "ROŚLINY"),
    ("Pischa", "Ceniona za właściwości wzmacniające wytrzymałość organizmu. Prawie pozbawiona smaku.", "ROŚLINY"),
    ("Bagienne ziele", "Cenione za właściwości otwierające umysł, lecz w dużych dawkach niebezpieczne. Smakuje szlamem.", "ROŚLINY"),
    ("Mandragora", "Ceniona za właściwości pobudzające i zwiększające możliwości fizyczne w walce. W smaku gorzkawa.", "ROŚLINY"),
    ("Kolcolist", "Preferuje gleby suche. Ceniony jako składnik wzmacniający działanie wielu mikstur.", "ROŚLINY"),
    ("Wilcza jagoda", "W zależności od dawki w miksturach leczniczych lub truciznach. Słodka i przyjemna.", "ROŚLINY"),
    ("Aloesowiec", "Dość pospolity gatunek kaktusa, cenione źródło wody pitnej na pustyni.", "ROŚLINY"),
    ("Aloes jaszczurzy", "Rzadka roślina ceniona jako źródło wody pitnej na pustyni. Łagodny, lekko cytrusowy smak.", "ROŚLINY"),
    ("Oko driady", "Cenione za działanie wyostrzające czułość zmysłów i poprawiające percepcję.", "ROŚLINY"),
    ("Ziele podróżnika", "Rośnie niemal wszędzie, choć nieczęsto. Ratunek dla wyczerpanych wędrówką.", "ROŚLINY"),
    ("Siężygron", "Popularne ziele cenione za właściwości lecznicze, mimo bardzo cierpkiego smaku.", "ROŚLINY"),
    ("Czosnek polny", "Ceniony za walory smakowe i właściwości wzmacniające zdrowie.", "ROŚLINY"),
    ("Pędy konopne", "Nadające się do przetworzenia pędy konopne.", "ROŚLINY"),
    ("Pędy lnu", "Można je przetworzyć na olej albo włókno lniane.", "ROŚLINY"),
    # ── GRZYBY ─────────────────────────────────────────────────────────────────
    ("Muchomor jaskiniowy", "Występuje głównie na terenach górskich, w jaskiniach i podziemnych korytarzach. Składnik mukhomorku.", "GRZYBY"),
    ("Świeciec opętak", "Dość rzadko spotykany w jaskiniach i tunelach górskich. Wydziela słabe, zielonkawe światło.", "GRZYBY"),
    ("Wronka smaczna", "Charakterystyczny, czarny grzyb o cenionych walorach smakowych. Nie nadaje się do suszenia.", "GRZYBY"),
    ("Leśny książę", "Bardzo ceniony za walory smakowe oraz pożywność.", "GRZYBY"),
    ("Trufla ostwaldzka", "Przez wielu uważana za najsmakowitszy grzyb świata. Wyglądem przypomina czerwono-brązowy kamień.", "GRZYBY"),
    ("Gryfie jajo", "Dość rzadka, jadalna purchawica najczęściej występująca w lasach i górach Amarth.", "GRZYBY"),
    ("Miodziaj kruchy", "Dość rzadki grzyb o charakterystycznym miodowym smaku i zapachu.", "GRZYBY"),
    ("Miodziaj jadowity", "Dość rzadko spotykany grzyb łudząco podobny do miodziaja kruchego, jednak silnie trujący.", "GRZYBY"),
    ("Drabant brunatny", "Smakowity i pożywny grzyb o szerokim zastosowaniu kulinarnym.", "GRZYBY"),
    ("Śluzica jadalna", "Galaretowaty, półpłynny, zielonkawy grzyb chętnie rosnący na cmentarzach.", "GRZYBY"),
    ("Szeptun modraczek", "Dość rzadki, niepozorny, niebieski grzybek. Ceniony w medycynie ludowej jako łagodne antidotum.", "GRZYBY"),
    ("Muchomor olbrzymi", "Dość rzadki grzyb o przyjemnym smaku i właściwościach łagodnej trucizny.", "GRZYBY"),
    ("Jadownica purpurowa", "Rzadki, silnie trujący grzyb; w małych dawkach powoduje długotrwałe splątanie i psychozę.", "GRZYBY"),
    ("Wróży kielich", "Bardzo rzadki grzyb o silnych halucynogennych właściwościach. Spożyty może być śmiertelnie trujący.", "GRZYBY"),
    ("Wiązówka księżycowa", "Dość rzadki grzyb porastający pnie drzew; właściwości zależą od fazy Luminusa.", "GRZYBY"),
    ("Mięsnik górski", "Rośnie głównie w jaskiniach, bezpośrednio na wilgotnej skale. Stanowi główne pożywienie krasnoludów.", "GRZYBY"),
    # ── DREWNO ─────────────────────────────────────────────────────────────────
    ("Drewno", None, "DREWNO"),
    ("Drewno klonowe", "Pospolite, niedrogie i dość uniwersalne drewno.", "DREWNO"),
    ("Drewno bukowe", "Pospolite, niedrogie i dość twarde drewno.", "DREWNO"),
    ("Drewno cisowe", "Rzadko spotykany rodzaj drewna znany z wyjątkowej wytrzymałości i elastyczności.", "DREWNO"),
    ("Drewno dębowe", "Dość rzadkie, szlachetne, twarde, ale zarazem wystarczająco sprężyste drewno.", "DREWNO"),
    ("Drewno jesionowe", "Drewno cenione za swoją wytrzymałość i sprężystość.", "DREWNO"),
    ("Drewno sosnowe", "Bardzo pospolite. Nadaje się na materiał budowlany albo opał.", "DREWNO"),
    ("Drewno maklurowe", "Rzadkie, szlachetne drewno o znakomitej wytrzymałości i elastyczności.", "DREWNO"),
    ("Drewno elnurilowe", "Wyjątkowo rzadkie, szlachetne drewno o znakomitej wytrzymałości i elastyczności.", "DREWNO"),
    # ── TKANINY ────────────────────────────────────────────────────────────────
    ("Juta", None, "TKANINY"),
    ("Bawełna", "Surowe włókno dojrzałej bawełny.", "TKANINY"),
    ("Wełna", "Miękkie, puszyste, surowe włókno wełniane.", "TKANINY"),
    ("Tkanina bawełniana", "Miękka i uniwersalna tkanina, jednak o zaledwie średniej wytrzymałości.", "TKANINY"),
    ("Tkanina wełniana", "Wytrzymała, dość popularna, gruba, miękka i ciepła tkanina o dość grubym splocie.", "TKANINY"),
    ("Tkanina konopna", "Pospolita, dość szorstka, bardzo wytrzymała tkanina idealna na żagle, pościel czy obrusy.", "TKANINY"),
    ("Tkanina lniana", "Grubsza, dość szorstka tkanina o dużej odporności na rozciąganie i tarcie.", "TKANINY"),
    ("Wełniany filc", "Wytrzymały, gruby i sztywny materiał używany najczęściej do wyrobu kapeluszy i obuwia.", "TKANINY"),
    ("Atłas", "Rzadka, kosztowna i bardzo elegancka tkanina wykonana z nici jedwabnych.", "TKANINY"),
    ("Satyna", "Jedna z popularniejszych tkanin wykonanych z jedwabiu, elegancka, miękka i dość wytrzymała.", "TKANINY"),
    ("Szantung", "Dość często spotykana tkanina jedwabna o nieregularnej strukturze.", "TKANINY"),
    ("Aksamit", "Rzadka i kosztowna tkanina wykonana z nici bawełnianych i jedwabnych.", "TKANINY"),
    ("Brokat", "Niezwykle rzadka i bardzo kosztowna tkanina wykonana z połączenia nici jedwabnych i złota.", "TKANINY"),
    # ── NICI ───────────────────────────────────────────────────────────────────
    ("Nici jedwabne", "Cienkie i mocne, o pięknym połysku.", "NICI"),
    ("Nici bawełniane", "Cienkie, estetyczne, ale niezbyt mocne.", "NICI"),
    ("Nici konopne", "Grube, matowe, szorstkie i bardzo mocne.", "NICI"),
    ("Nici lniane", "Dość grube, matowe i mocne.", "NICI"),
    ("Nici wełniane", "Grube i mocne nici wykonane z wełny.", "NICI"),
    ("Nici metaliczne", "Jedwabne nici pokryte najprawdziwszym złotem! Bardzo cenny surowiec do produkcji brokatowych tkanin.", "NICI"),
    ("Surowe nici jedwabne", "Nici surowego jedwabiu gotowe do dalszej obróbki lub do wytworzenia szantungu.", "NICI"),
    ("Kokon jedwabnika", "Rzadko spotykany i w idealnym stanie owadzi kokon doskonały jako surowiec do nici jedwabnych.", "NICI"),
    # ── ŻYWNOŚĆ ────────────────────────────────────────────────────────────────
    ("Dziki agrest", "Niewielka, orzeźwiająca przekąska.", "ŻYWNOŚĆ"),
    ("Zielone jabłko", "Soczyste, zdrowe i pyszne!", "ŻYWNOŚĆ"),
    ("Bochenek chleba", "Pięknie pachnie. I ta zarumieniona skórka…!", "ŻYWNOŚĆ"),
    ("Pożywny banan", "Smakowity i dodaje sił witalnych.", "ŻYWNOŚĆ"),
    ("Kawałek sera", "Pożywny i smakowity. A do zapachu można się przyzwyczaić.", "ŻYWNOŚĆ"),
    ("Suszony drób", "Lepiej smakuje niż wygląda. Raczej nie dla Elfów.", "ŻYWNOŚĆ"),
    ("Suszone mięso", "Lepiej wygląda niż smakuje. Raczej nie dla Elfów.", "ŻYWNOŚĆ"),
    ("Pieczone udko", "Aromatyczna i pożywna porcja pieczonego mięsa.", "ŻYWNOŚĆ"),
    ("Pieczona tiruba", "Niewielka, ale smakowita ryba.", "ŻYWNOŚĆ"),
    ("Pieczone żeberka", "Aromatyczna i pożywna porcja pieczonego mięsa.", "ŻYWNOŚĆ"),
    ("Pieczone szczypce kraba", "Smakowite, delikatne mięso.", "ŻYWNOŚĆ"),
    ("Surowe udko", "Surowe udko w sam raz do pieczenia!", "ŻYWNOŚĆ"),
    ("Surowa tiruba", "Surowa tiruba w sam raz do pieczenia!", "ŻYWNOŚĆ"),
    ("Surowe żeberka", "Surowe żeberka w sam raz do pieczenia!", "ŻYWNOŚĆ"),
    # ── TROFEA ─────────────────────────────────────────────────────────────────
    ("Szczypce kraba", "Po odpowiednim przetworzeniu mogą służyć za pożywienie lub składnik mikstur.", "TROFEA"),
    ("Spetryfikowane szczypce kraba", "Trudny do pozyskania, cenny składnik alchemiczny.", "TROFEA"),
    ("Ząb drapieżnika", "Nieczęsto zdobywany ząb jakiegoś niebezpiecznego stworzenia.", "TROFEA"),
    ("Zwykły ząb", "Wygląda na zupełnie zwykły ząb.", "TROFEA"),
    ("Unikatowy ząb potwora", "Taki kieł to prawdziwa rzadkość!", "TROFEA"),
    ("Pospolite pazury", "Jedno z najczęściej spotykanych trofeów myśliwskich.", "TROFEA"),
    ("Unikatowe pazury", "Wyjątkowe i cenne trofeum myśliwskie.", "TROFEA"),
    ("Pospolity róg", "Róg, jakich wiele wala się po Fallathanie.", "TROFEA"),
    ("Unikatowy róg", "Ten róg należał do jakiegoś wyjątkowo rzadkiego zwierzęcia.", "TROFEA"),
    ("Barwne pióro", "Rzadko spotykane, wyjątkowo ładne pióro.", "TROFEA"),
    ("Zwykłe pióro", "Pióro ze skrzydła lub ogona sporego, ale dość pospolitego ptaka.", "TROFEA"),
    ("Biała perła", "Rzadka i bardzo cenna!", "TROFEA"),
    ("Szara perła", "Rzadka i bardzo cenna!", "TROFEA"),
    ("Koral szlachetny", "Fragment szkieletu koralowca; rzadki i ceniony w jubilerstwie.", "TROFEA"),
    ("Mała muszelka", "Najzwyklejsza, pospolita muszelka. Po sproszkowaniu bywa wykorzystywana w miksturach wzmacniających.", "TROFEA"),
    ("Złocista muszelka", "Rzadko spotykana muszla. Po sproszkowaniu bywa wykorzystywana w miksturach wzmacniających.", "TROFEA"),
    ("Serce potwora", "Dużym zaskoczeniem było to, że potwory mają zielone serca. Jeszcze większym — jak cenne są te serca w alchemii.", "TROFEA"),
    ("Ości tiruby", "Bezużyteczne tylko na pierwszy rzut oka. Ości tej ryby umożliwiają produkcję wyjątkowo lepkiej substancji.", "TROFEA"),
    # ── SKÓRY I FUTRA ──────────────────────────────────────────────────────────
    ("Zwykła skóra", "Niewyprawiona skóra z pospolitego zwierzęcia.", "SKÓRY I FUTRA"),
    ("Gruba skóra", "Niewyprawiona skóra z jakiegoś potężnego zwierzęcia.", "SKÓRY I FUTRA"),
    ("Szlachetna skóra", "Niewyprawiona skóra z jakiegoś rzadkiego zwierzęcia.", "SKÓRY I FUTRA"),
    ("Zwykła wyprawiona skóra", "Wyprawiona skóra z pospolitego zwierzęcia.", "SKÓRY I FUTRA"),
    ("Gruba wyprawiona skóra", "Wyprawiona skóra z jakiegoś potężnego zwierzęcia.", "SKÓRY I FUTRA"),
    ("Szlachetna wyprawiona skóra", "Wyprawiona skóra z jakiegoś rzadkiego zwierzęcia.", "SKÓRY I FUTRA"),
    ("Rzemień", "Długi, cienki pasek wyprawionej skóry, bardzo wytrzymały.", "SKÓRY I FUTRA"),
    ("Zwykłe futro", "Duży kawałek dość pospolitego, ale dobrej jakości niewyprawionego futra.", "SKÓRY I FUTRA"),
    ("Szlachetne futro", "Duży kawałek rzadkiego i doskonałej jakości niewyprawionego futra.", "SKÓRY I FUTRA"),
    ("Zwykłe wyprawione futro", "Duży kawałek dość pospolitego, ale dobrej jakości wyprawionego futra.", "SKÓRY I FUTRA"),
    ("Szlachetne wyprawione futro", "Duży kawałek rzadkiego i doskonałej jakości wyprawionego futra.", "SKÓRY I FUTRA"),
    ("Fragment futra", "Średniej wielkości kawałek futra, który może zainteresować kuśnierza.", "SKÓRY I FUTRA"),
    # ── SKŁADNIKI ALCHEMICZNE ──────────────────────────────────────────────────
    ("Zmurszała kość", "Częsty, choć niezbyt apetyczny składnik mikstur alchemicznych.", "SKŁADNIKI ALCH."),
    ("Kość umarlaka", "Musi być świeża! Rzadki składnik alchemiczny, o którym większość woli nie wiedzieć.", "SKŁADNIKI ALCH."),
    ("Kości zwierzęce", "Muszą być świeże! Dość pospolity składnik alchemiczny.", "SKŁADNIKI ALCH."),
    ("Sproszkowane kości", "Dla wielu proszek ze zwierzęcych kości to nic przyjemnego, jednak niejeden alchemik uzna je za przydatne.", "SKŁADNIKI ALCH."),
    ("Sproszkowana kość umarlaka", "Cenny i trudnodostępny składnik alchemiczny, o którym większość woli nie wiedzieć.", "SKŁADNIKI ALCH."),
    ("Pasta szlifierska", "Specjalna pasta umożliwiająca obróbkę kamieni nieszlachetnych i kryształów.", "SKŁADNIKI ALCH."),
    ("Pasta diamentowa", "Specjalna, bardzo cenna pasta umożliwiająca obróbkę kamieni szlachetnych.", "SKŁADNIKI ALCH."),
    ("Wywar garbarski", "Specjalnie przygotowany wywar z kory sosnowej używany do wyprawiania zwykłych zwierzęcych skór.", "SKŁADNIKI ALCH."),
    ("Szlachetny wywar garbarski", "Specjalnie przygotowany wywar z kory sosnowej używany do wyprawiania zwierzęcych futer i szlachetnych skór.", "SKŁADNIKI ALCH."),
    ("Olej lniany", "Niezbędny do impregnacji drewnianych przedmiotów. Poza tym przydatny w kuchni, laboratorium i u cyrulika.", "SKŁADNIKI ALCH."),
    ("Smoła", "Czarne paskudztwo przydatne w rzemieślnictwie.", "SKŁADNIKI ALCH."),
    ("Żywica sosnowa", "Gęsta, lepka substancja o bursztynowym kolorze i intensywnym leśnym zapachu.", "SKŁADNIKI ALCH."),
    ("Czarny proch", "Cenny, trudny do zdobycia materiał wybuchowy, wytwarzany przez nielicznych alchemików.", "SKŁADNIKI ALCH."),
    ("Zacier zbożowy", "Gęsta, mętna, lekko pienista substancja wytworzona z ziaren zbóż, będąca bazą w produkcji najmocniejszych alkoholi.", "SKŁADNIKI ALCH."),
    ("Olejokoktail", "Dość popularna mieszanka oleju lnianego i okowity wykorzystywana w wyższej klasy broni alchemicznej.", "SKŁADNIKI ALCH."),
    ("Dusza wiedźmy", "Dość popularny mocny alkohol będący nalewką z okowity i wilczej jagody; stosowany jako trucizna lub paliwo.", "SKŁADNIKI ALCH."),
    ("Wódka ordynaryjna", "Dość popularny, mocny i cierpki w smaku trunek wytworzony w procesie kilkukrotnej destylacji.", "SKŁADNIKI ALCH."),
    ("Mukhomork", "Mocny trunek wytwarzany z muchomorów jaskiniowych według krasnoludzkiej receptury.", "SKŁADNIKI ALCH."),
    ("Okowita", "Bardzo mocny, dość czysty alkohol będący efektem wielokrotnej, żmudnej destylacji.", "SKŁADNIKI ALCH."),
    ("Smołokoktajl", "Dość popularna mieszanka smoły i okowity wykorzystywana w wyższej klasy broni alchemicznej.", "SKŁADNIKI ALCH."),
    ("Płynny ogień", "Rzadko spotykana, ceniona mieszanka smoły, okowity i czarnego prochu stosowana w najwyższej jakości broni alchemicznej.", "SKŁADNIKI ALCH."),
    ("Lunar", "Wykonany z lunaridium pojemnik wypełniony Czystą Energią niezbędną do wytwarzania magicznych wzmacniaczy.", "SKŁADNIKI ALCH."),
    # ── NARZĘDZIA ──────────────────────────────────────────────────────────────
    ("Narzędzia kowalskie", "Zestaw narzędzi niezbędnych do obróbki metali, w tym wytwarzania z nich broni.", "NARZĘDZIA"),
    ("Narzędzia ciesielskie", "Zestaw narzędzi niezbędnych do obróbki drewna, w tym wytwarzania z niego broni.", "NARZĘDZIA"),
    ("Narzędzia płatnerskie", "Zestaw narzędzi niezbędnych do obróbki metali i skór, w tym wytwarzania z nich zbroi.", "NARZĘDZIA"),
    ("Narzędzia różdżkarskie", "Zestaw narzędzi niezbędnych do wytwarzania magicznych wzmacniaczy.", "NARZĘDZIA"),
    ("Narzędzia garbarskie", "Zestaw narzędzi niezbędnych do obróbki skór i futer.", "NARZĘDZIA"),
    ("Narzędzia lapidarne", "Zestaw narzędzi niezbędnych do obróbki niewielkich kamieni pospolitych i szlachetnych.", "NARZĘDZIA"),
    ("Narzędzia przędzalnicze", "Zestaw narzędzi niezbędnych do wytwarzania nici.", "NARZĘDZIA"),
    ("Narzędzia tkackie", "Zestaw podstawowych narzędzi niezbędnych do wytwarzania rozmaitych tkanin.", "NARZĘDZIA"),
    ("Narzędzia rusznikarskie", "Zestaw narzędzi niezbędnych do wytwarzania broni palnej i ogniowej.", "NARZĘDZIA"),
    ("Narzędzia formierskie", "Zestaw narzędzi niezbędnych do nadawania przedmiotom określonych kształtów.", "NARZĘDZIA"),
    ("Przybory alchemiczne", "Zestaw narzędzi niezbędnych do wytwarzania bomb i mikstur alchemicznych.", "NARZĘDZIA"),
    ("Przybory konstruktorskie", "Zestaw narzędzi niezbędnych do wytwarzania planów przedmiotów i różnych specyfików.", "NARZĘDZIA"),
    ("Przybory krawieckie", "Zestaw narzędzi niezbędnych do obróbki tkanin i skór, w tym do wytwarzania z nich ubrań.", "NARZĘDZIA"),
    ("Przybory kuchenne", "Zestaw narzędzi niezbędnych do przyrządzania rozmaitych dań i przetworów.", "NARZĘDZIA"),
    ("Nicielnica atłasowa", "Narzędzie uzupełniające zestaw tkacki, umożliwiające wytworzenie tkaniny o atłasowym splocie.", "NARZĘDZIA"),
    ("Naciąg satynowy", "Narzędzie uzupełniające zestaw tkacki, umożliwiające wytworzenie tkaniny o satynowym splocie.", "NARZĘDZIA"),
    # ── POJEMNIKI ──────────────────────────────────────────────────────────────
    ("Butelka cynowa", "Rzadko stosowany pojemnik alchemiczny.", "POJEMNIKI"),
    ("Butelka szklana", "Często używany pojemnik przydatny w alchemii.", "POJEMNIKI"),
    ("Butelka gliniana", "Popularny pojemnik przydatny w alchemii.", "POJEMNIKI"),
    ("Pusty bukłak", "Trochę przecieka, ale nowy właściciel na pewno jakoś sobie z tym poradzi.", "POJEMNIKI"),
    ("Pusta sakiewka", "Nic w niej nie ma, ale może ktoś akurat potrzebuje pustej.", "POJEMNIKI"),
    ("Płócienny worek", "Nie jest nawet za bardzo przetarty!", "POJEMNIKI"),
    # ── DOKUMENTY I PAPIER ────────────────────────────────────────────────────
    ("Glejt Teleportacyjny", "Dokument pozwala skorzystać z obelisku teleportacyjnego bez opłaty.", "DOKUMENTY"),
    ("Papier", "Zwój niezłej jakości papieru, na którym można coś zapisać.", "DOKUMENTY"),
    ("Papier konstruktorski", "Specjalistyczny i trudnodostępny papier umożliwiający rozrysowanie i zapisywanie planów.", "DOKUMENTY"),
    ("Prosta forma do mozaiki", "Forma niezbędna do wytworzenia niewielkiej mozaiki.", "DOKUMENTY"),
    ("Złożona forma do mozaiki", "Forma niezbędna do wytworzenia bardziej złożonej mozaiki.", "DOKUMENTY"),
    ("Kunsztowna forma do mozaiki", "Forma niezbędna do wytworzenia skomplikowanej i szczególnie cennej mozaiki.", "DOKUMENTY"),
    ("Przeminęło z anomalią", "Wzruszająca, ekscytująca i skomplikowana historia miłosna. Piękne wydanie!", "DOKUMENTY"),
    # ── INNE / HANDEL ──────────────────────────────────────────────────────────
    ("Kawałek szkła", "Niestety! To jedynie kawałek szkła. Ale może do czegoś się przyda...", "INNE"),
    ("Zwykły kamień", "Najzwyklejszy kawałek pospolitej skały.", "INNE"),
    ("Kamień", None, "INNE"),
    ("Grudka gliny", "Ilasta skała osadowa, która łatwo daje się formować i utrwalać.", "INNE"),
    ("Prymitywna maska", "Rytualna? Teatralna? Niech nowy właściciel się nad tym zastanawia…", "INNE"),
    ("Kościany talizman", "Z pewnością ktoś w Fallathanie kolekcjonuje takie dziwne rzeczy.", "INNE"),
    ("Stary róg", "Raczej do niczego już nie posłuży, ale można go położyć nad kominkiem.", "INNE"),
    ("Stary rytualny sztylet", "Zupełnie tępy, ale może zainteresować kolekcjonera.", "INNE"),
    ("Prymitywny naszyjnik", "Może znajdzie się ktoś wystarczająco ekscentryczny, żeby to kupić.", "INNE"),
    ("Kościany kilof", "Kilof z kości? Bardzo dziwny pomysł, ale może zaintryguje kogoś.", "INNE"),
    ("Prosty młotek", "Głowica tego młotka tylko trochę chwieje się na trzonku.", "INNE"),
    ("Fragment zatartej tabliczki", "Tak długo leżała w piasku, że napisy całkiem się zatarły.", "INNE"),
    ("Dziwny krzemień", "Krzemień z czaszką? To nie wygląda dobrze. Ale powinno się sprzedać.", "INNE"),
    ("Prosty jaszczurczy wisior", "To chyba niestety nie jest złoto, ale i tak ma szansę się sprzedać.", "INNE"),
    ("Futrzany chwost", "Trochę wyliniały, ale nadal elegancko dynda.", "INNE"),
    ("Pęknięta nordska tarcza", "W walce byłaby bezużyteczna, ale nad kominkiem powiesić można.", "INNE"),
    ("Amulet z czaszki wiewiórki", "Amulet z czaszki wiewiórki…?! Może znajdzie się jakiś szaleniec.", "INNE"),
    ("Moneta kultystów", "Hmm… Po co właściwie kultystom takie monety?", "INNE"),
    ("Amulet szczęścia", "Cynowy krążek z dziurką, który raczej nie ma szans działać.", "INNE"),
    ("Szamański amulet", "Nie wygląda na to, żeby kiedykolwiek działał, ale może znajdzie się kupiec.", "INNE"),
    ("Drewniana łyżka", "Można nią jeszcze nieźle zamieszać! Na pewno jakiś Halfita ją kupi.", "INNE"),
    ("Prosta fujarka", "Od biedy nawet da się z niej wydobyć jakieś dźwięki.", "INNE"),
    ("Lekko nadpalona świeca", "Prawie nowa świeca zawsze się komuś przyda.", "INNE"),
    ("Głodny but", "Trochę śmierdzi. Tego to chyba nikt nie kupi.", "INNE"),
    ("Rytualna tabliczka", "Jaszczury używają ich podczas pochówków.", "INNE"),
    ("Stary kilof", "Nie wygląda zbyt solidnie, ale może kupiec się nie zorientuje?", "INNE"),
    ("Podniszczona miniatura portretowa", "Trudno powiedzieć, kogo mogła przedstawiać w czasach swej świetności.", "INNE"),
]


def run():
    app = create_app()
    with app.app_context():
        added = 0
        skipped = 0
        for name, description, category in ITEMS:
            if Item.query.filter_by(name=name).first():
                skipped += 1
                continue
            item = Item(
                name=name,
                category=category,
                description=description,
                aliases=[],
                tags=[],
                display_order=0,
            )
            db.session.add(item)
            added += 1

        db.session.commit()
        print(f"Zaimportowano: {added} surowców, pominięto {skipped} (już istniały).")
        print(f"Łącznie w bazie: {Item.query.count()} surowców.")


if __name__ == "__main__":
    run()
